### ISSUE TITLE
!thinkid is actually !fatkid

### ISSUE THREAD

**Issue by mieite** [kitsun8/K8Gatheriino#23]
!thinkid is calling !fatkid. Should be an easy fix.

**Comment by nvirm** [comment]
https://github.com/kitsun8/K8Gatheriino/blob/84d9e9e89ab61e39c3af1f62833400d6b33a60d4/project/K8GatherBot-v2/Program.cs#L700

Oh boi.

**Comment by nvirm** [comment]
Fixed with https://github.com/kitsun8/K8Gatheriino/commit/a2d180a952110a16da06e0a744b561eb500985bd
